import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>{/* TODO チェックボックス実装 */}</div>

        <div>{/* TODO 表実装 */}</div>
      </main>
    </div>
  )
}

export default Home
