import PopulationPerYearChart from 'components/population-per-year-chart'
import PrefectureCheckboxes from 'components/prefecture-checkboxes'
import type { NextPage } from 'next'
import Head from 'next/head'
import useAxios, { PREFETURES_FRONTEND_PATH } from 'utils/hooks/useAxios'
import useCheckedPrefectures from 'utils/hooks/useCheckedPrefectures'
import { Prefecture, RESASSuccessResponse } from 'utils/resas/types'

const Home: NextPage = () => {
  const { checkedPrefectures, populationPerYear, ...func } =
    useCheckedPrefectures()

  const {
    data,
    isError: prefecturesIsError,
    isLoading: prefectureIsLoading,
  } = useAxios<RESASSuccessResponse<Prefecture[]>>(PREFETURES_FRONTEND_PATH)

  const prefectures = data ? data.result : []

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          {data ? (
            <PrefectureCheckboxes prefectures={data.result} {...func} />
          ) : prefectureIsLoading ? (
            <>読込中</>
          ) : (
            <>エラー</>
          )}
        </div>

        <div>
          <PopulationPerYearChart
            populationPerYear={populationPerYear}
            prefectures={prefectures}
          />
        </div>
      </main>
    </div>
  )
}

export default Home
